### ISSUE TITLE
Lore not adding to Spellbook when visiting URL

### ISSUE THREAD

**Issue by mzomzo** [Magikcraft/product-board#20]
When I visit the URL provided by the game for new spell lore, the lore doesn't show up.

- Video showing the issue here: http://recordit.co/bY3nvtBO52
- Image showing some server related issues in the Minecraft console upon logging in: https://files.slack.com/files-pri/T1LBET7TJ-F6YJ5R7CJ/image.png

The one Lore that does show up for me is from going through the tour which worked fine.

**Comment by jwulf** [comment]
Thanks for reporting this @mzomzo.

The server-related issues are due to no default `package.json` being generated for users.

The lore not showing up is an odd one. @triyuga ?

**Comment by jwulf** [comment]
**Cause**: The GraphQL server was erroneously filtering all events for non-Admin users. 

**Consequence**: This meant that no events were triggered for non-admin users - including the event that triggers insertion of a new lore.

**Fix**: The filter was removed from the GraphQL events handler.

**Result**: Lore now posts to the spellbook for all users, as expected.

**Comment by jwulf** [comment]
<img width="553" alt="screen shot 2017-09-07 at 8 45 48 am" src="https://user-images.githubusercontent.com/406975/30137920-fc41ff10-93a8-11e7-909d-dbe9517d4cf3.png">
