### ISSUE TITLE
Make a Magikcraft Lobby

### ISSUE THREAD

**Issue by jwulf** [Magikcraft/product-board#21]
# User Story

As a user, I can have a place to be AFK and I don't have to find out the name of the warps I can just step through a portal and I am warped.

# Background

This is useful because it is a place for Magikcraft players to stay in and be safe. It can also have convenient teleportation pads for players e.g. Minigame worlds

# Feature Description

This lobby is a fancy place with a magikal vibe and there will be lots of annotated teleporters.

# Out of Scope

Great things that can be done in version 2:
Nothing here yet.

# Acceptance Criteria

The following need to function to consider this feature complete:
When someone can complete the tutorial and then go to a lobby which can take them anywhere and they can purchase items from a store.

# User Acceptance Test Plan

Here is the process for testing this feature:
Getting players to go on and see if they find it more convenient.

# End-User Documentation

_[Docs that can be copypasta to the user docs]_
Nothing here yet.

**Comment by Technosasquach** [comment]
Due to how a lobby needs to work, the 'world' world has been modified to accomodate this as a MVP. Ultimately the need for a more advanced spawning mechanism is required.

**Comment by jwulf** [comment]
Param has made one. It needs some more work to integrate it - portals need to be wired up, and it needs to be made the default spawn point.

**Comment by jwulf** [comment]
`/warp lobby` to get there.
