### ISSUE TITLE
Add link to Slack to Play App

### ISSUE THREAD

**Issue by jwulf** [Magikcraft/product-board#31]
# User Story

As a user I can sign up to the School of Magik Slack from the Play App.

# Background

At the moment users can find out about the [School of Magik Slack](https://slack.magikcraft.io) only from the Getting Started Guide at [start.magikcraft.io](https://start.magikcraft.io).

# Feature Description

This will put a link to [slack.magikcraft.io](https://slack.magikcraft.io) in the Play App itself, so that users can discover it and sign up from there.

**Comment by tim-marwick** [comment]
This has been added to the private-product-board instead! 

https://github.com/Magikcraft/private-product-board/issues/66

Closing.
