### ISSUE TITLE
Add link to Getting Started Guide in Play App

### ISSUE THREAD

**Issue by jwulf** [Magikcraft/product-board#32]
# User Story

As a user I can access the Getting Started Guide from the Play App.

# Background

At the moment we have documentation that we can edit and update via Corilla at [start.magikcraft.io](https://start.magikcraft.io), but there is no easy and obvious way to discover it.

# Feature Description

This feature makes it possible for a user to discover the Getting Started Guide from the Play App.

**Comment by tim-marwick** [comment]
Retiring this in favour of in-context documentation. Today I added the ability to pull content directly from Github into the PlayApp via the `GithubContent` component. This is now the preferred way of providing user documentation.
