### ISSUE TITLE
Run Minecraft on Raspberry Pi

### ISSUE THREAD

**Issue by jwulf** [Magikcraft/product-board#33]
https://www.novaspirit.com/2017/03/09/install-desktop-version-minecraft-raspberry-pi/

**Comment by jwulf** [comment]
This is necessary for https://github.com/MozillaFoundation/mozfest-program-2017/issues/250

**Comment by Rahuuuul** [comment]
This Wouldn't really work because Minecraft on rasberry pi is like the first Minecraft PE. Is that right or have i missed something?

**Comment by jwulf** [comment]
There is a way to get the full Minecraft to run on a Raspberry Pi, at least up to version 1.8.9.

Mozfest is past now. Joe Nash from GitHub did a great job of running the workshop.
