### ISSUE TITLE
Please make sugimisu and tkc49 admin for Japan server

### ISSUE THREAD

**Issue by jwulf** [Magikcraft/product-board#35]
Please make users sugimisu (Minecraft name cybersugimisu) and tkc49, admins for the Japan server.

**Comment by tim-marwick** [comment]
This is already the case for `tkc49`, since a few months now. 

I note `tkc49` has actually not logged in since we deleted all the `githubtokens` to request new perms for the github integration (over a month ago).

I added `sugimisu` as an admin on the `ja.open.magikcraft.io` server.
