### ISSUE TITLE
Spell syncing broken

### ISSUE THREAD

**Issue by jwulf** [Magikcraft/product-board#36]
Spells are synchronised initially, but changes to spells do not sync to the production server.

To reproduce:
* Connect to magikcraft.io in Minecraft
* Edit an existing spell or create a new spell
* Cast the spell - for a new spell, you get `You do not have the spell <spellname>`. For existing spells, the old version runs.

呪文は最初は同期されていますが、呪文への変更は本番サーバーに同期されません。

再現するには：

* Minecraftのmagikcraft.ioに接続してください。
*既存の呪文を編集するか、新しい呪文を作成する。
*呪文を唱える - 新しい呪文の場合、「`You do not have the spell <spellname>`」と表示されます。 既存の呪文は、古いバージョンが実行されます。

**Comment by jwulf** [comment]
Hmmm.... not sure why, but this seems to be working fine now. Weird.

**Comment by tim-marwick** [comment]
Yeah, I noticed this is sometimes the case, but not consistently. Mostly, it seems to work.

In order to debug we'll need a reliable reproducer...
