### ISSUE TITLE
Mediarite's spellbook lints an error for `magik.memento.setItem()`

### ISSUE THREAD

**Issue by jwulf** [Magikcraft/product-board#48]
Observed while MEDIARITE was recording a video. 

The intellisense in his spellbook linted `magik.memento.setItem()` as an error in the following code (from the `memento` scroll):

```typescript
const magik = magikcraft.io;

function recall(name){
    const memory = magik.memento.getItem(name);
    magik.dixit(memory);
}
```

**Comment by jwulf** [comment]
<img width="462" alt="screen shot 2017-11-26 at 10 20 29 pm" src="https://user-images.githubusercontent.com/406975/33239909-308754b2-d2f8-11e7-8f4f-de9e3e0c2e9f.png">

Can reproduce using the login link for Mediarite.

According to the network inspector, it is requesting [https://api.github.com/repos/Magikcraft/play-app-intellisense/contents/magikcraft.io.d.ts](https://api.github.com/repos/Magikcraft/play-app-intellisense/contents/magikcraft.io.d.ts).

**Comment by jwulf** [comment]
@triyuga any idea about this?

**Comment by jwulf** [comment]
Observed last night in the wild with a bunch of peeps at the DDD Event.

**Comment by tim-marwick** [comment]
@jwulf I looked at this and it looks like that bug was called by the GitHub API rate_limit getting exhausted for the user. I fixed this by moving to a GitHub raw URL for Intellisense.

**Comment by tim-marwick** [comment]
Tested as MEDIARITE and works! Closing!
